### ISSUE TITLE
resource temporarily unavailable?

### ISSUE THREAD

**Issue by xibz** [mdlayher/vsock#24]
I cannot seem to ever to get past the resource temporarily unavailable error. It seems to retry a bunch, but never succeeds in a connection. This may not even pertain to this library, but any clue to why this is occurring would be great!

**Comment by mdlayher** [comment]
For the time being, you'll have to handle that error yourself and keep looping.  In Go 1.12, we'll have proper runtime network poller support, and this will no longer be necessary.

/cc @mxpv

**Comment by YvesChan** [comment]
Same here. vscp doesn't work with Go 1.11.5. Perhaps you should modify the Go version requirements in README.md?

**Comment by mdlayher** [comment]
Please upgrade to Go 1.12. See #25.

**Comment by mdlayher** [comment]
Fixed as of https://github.com/mdlayher/vsock/pull/26.
