### ISSUE TITLE
Fd behind the Conn?

### ISSUE THREAD

**Issue by paul-lalonde** [mdlayher/vsock#48]
Thanks for this great package - it does exactly what it says on the tin!

I need to pass the file descriptor to a vsock connection to a child process.  Is there a straightforward way to get the fd (or an os.File) from the Conn retured from Accept?

I know my type, and am willing to type assert.

**Comment by mdlayher** [comment]
Yep, see: https://pkg.go.dev/github.com/mdlayher/vsock#Conn.SyscallConn

This will give you access to methods that expose the file descriptor. Closing!

**Comment by paul-lalonde** [comment]
Genius - thanks!
