### ISSUE TITLE
how to simply add keepAlive feature in vsock like in use tcp socket?

### ISSUE THREAD

**Issue by brodyxchen** [mdlayher/vsock#52]
I search source code of golang net/http package, and found the keepAlive feature depends on linux syscall. 

// this is golang net/http source code in src/net/sockopt_posix.go: 118
func setKeepAlive(fd *netFD, keepalive bool) error {
	err := fd.pfd.SetsockoptInt(syscall.SOL_SOCKET, syscall.SO_KEEPALIVE, boolint(keepalive))
	runtime.KeepAlive(fd)
	return wrapSyscallError("setsockopt", err)
}

I am develop a new package like net/http,   depend on this vsock package instead of socket.
But I dont now how to add keepAlive with linux syscall.

**Comment by mdlayher** [comment]
If keep alive works on AF_VSOCK, that's your answer. If not, it's something the Linux kernel would have to support in order to allow us to use it. 

Note that we implement net.Listener and net/http just works over vsock. I don't think there's anything to do here, so closing.
