### ISSUE TITLE
is it possible to support windows ?

### ISSUE THREAD

**Issue by jeffrey4l** [mdlayher/vsock#56]
for example, i wanna to run a golang process listen on the vsock port in windows guest.

**Comment by mdlayher** [comment]
Sorry, non-Linux operating systems are out of scope for this package, but other users have built various shims to support them as well: https://pkg.go.dev/github.com/mdlayher/vsock?tab=importedby

**Comment by jeffrey4l** [comment]
sorry, still can not find any support for windows guest. through above link.

**Comment by zxysilent** [comment]
You can refer to this fork: [https://github.com/zxysilent/vsock](https://github.com/zxysilent/vsock) but it's not good enough yet.
